X "cd ~/PACKAGES/SovereignCrisis";

%INCLUDE "./sas/SETENVIR.sas";
%INCLUDE "./sas/0.CreateDataset.sas";
%INCLUDE "./sas/AGGREGATIONS.sas";
%INCLUDE "../WRDSHelpers/sas/quickfunctions.sas";
%INCLUDE "/wrds/wrdsmacros/winsorize.sas";
%INCLUDE "/wrds/wrdsmacros/nwords.sas";
%INCLUDE "/wrds/wrdsmacros/csv.sas";

PROC DATASETS LIB = BS;
QUIT;

PROC CONTENTS DATA = BS.BS_FINANCIALS OUT = _VARLIST VARNUM; RUN;
%CONTENTS(DATA = _VARLIST);
    
PROC SQL;
    CREATE TABLE _RATIOS AS
        SELECT NAME, LABEL
        FROM _VARLIST
        WHERE UPCASE(LABEL) LIKE "%RATIO%";
QUIT;

PROC PRINT DATA = _RATIOS; RUN;
PROC PRINT DATA = _VARLIST(KEEP = NAME LABEL); RUN;

PROC TRANSPOSE
    DATA = BS.BS_FINANCIALS
    OUT = BSFIN_LONG;
    BY CLOSDATE INDEX;
RUN;
%CONTENTS(DATA = BSFIN_LONG);
%PRINT(DATA = BSFIN_LONG);


%PREPROCESS_BANKSCOPE(OUT = BSFIN);

%CONTENTS(DATA = BSFIN);

PROC SORT DATA = BSFIN; BY CTRYCODE INDEX DATE; RUN;
PROC TRANSPOSE
    DATA = BSFIN 
    OUT = BSFIN_LONG;
    BY CTRYCODE INDEX DATE;
    VAR DATA2000 -- DATA38430;
RUN;

%CONTENTS(DATA = BSFIN_LONG);

%AGGREGATE(
    IN = BSFIN_LONG,
    OUT = BSFIN_AGGREGATED,
    BY = _NAME_ _LABEL_ CTRYCODE DATE,
    VAR = COL1
    );

LIBNAME HOME  '/scratch/uvanl';
%CSV(
    INSET = BSFIN_AGGREGATED,
    OUTSET = /scratch/uvanl/BSFIN_AGGREGATED);




/* PROC FREQ DATA = BS.BS_BANK; TABLE CONSOL SPECIAL; RUN; */
/* %CONTENTS(DATA = BS.BS_BANK); */

/* OPTIONS LS = 100; */
/* PROC MEANS DATA = __TEMP3__; RUN; */
/* PROC MEANS DATA = BS.BS_FINANCIALS; RUN; */
